import androidx.compose.ui.graphics.Color
import component_colors.DatePickerColors

data class AppColors(
    val mainBackgroundColor: Color,
    val mainBackgroundWindowDarkColor: Color,
    val mainDrawerBackground: Color,
    val mainToolbarColor: Color,
    val mainLeftBarColor: Color,
    val mainTextColor: Color,
    val mainTextColorLight: Color,
    val mainPlaceholderTextColor: Color,
    val mainIconsColor: Color,
    val mainIconsColorDark: Color,
    val selectedIconColor: Color,
    val cardBackgroundDark: Color,
    val cardBackgroundLight: Color,
    val tooltipAreaBackground: Color,
    val divider: Color,
    val dividerLight: Color,
    val searchBackground: Color,
    val searchBackgroundDark: Color,
    val searchIconColor: Color,
    val searchDescriptionTextColor: Color,
    val searchDividerColor: Color,
    val pointerIsActiveCardColor: Color,
    val pointerIsActiveCardColorDark: Color,
    val linkColor: Color,
    val datePickerColors: DatePickerColors,
    val errorColor: Color,
    val successColor: Color,
    val readingStatusesColor: ReadingStatusesColor,
    val textFieldColorOld: Color,
    val textFieldColorDarkOld: Color,
    val hintColor: Color,
    val focusedTextFillBackground: Color,
    val dropdownBackground: Color,
    val tooltipSelectedBackground: Color,
    val mainAddButtonColor: Color,
    val textDescriptionColor: Color,
    val primaryButtonColor: Color,
    val secondaryButtonColor: Color,
    val joinAuthorsColors: JoinAuthorsColors,
    val authorsContainerColor: Color,
    val adminPanelButtons: AdminPanelButtons,
    val titleColors: TitleColors,
    val screenColor: ScreenColor,
    val textFieldColor: TextFieldColor,
    val serviceDevelopmentStatusColor: ServiceDevelopmentStatusColor,
)

class ReadingStatusesColor(
    val plannedStatusColor: Color,
    val readingStatusColor: Color,
    val doneStatusColor: Color,
    val deferredStatusColor: Color,
)

class JoinAuthorsColors(
    val mainAuthorColor: Color,
    val relatesAuthorsColor: Color,
)

class AdminPanelButtons(
    val approvedColor: Color,
    val approvedWithChangesColor: Color,
    val disapprovedColor: Color,
    val uploadColor: Color,
)

class TitleColors(
    val booksTitleInfoColor: Color,
    val secondaryBooksTitleInfoColor: Color,
)

class ScreenColor(
    val background: Color,
    val appBarColor: Color,
    val iconColor: Color,
    val textColor: Color,
    val activeLinkColor: Color,
    val activeButtonColor: Color,
    val selectedTitleTextColor: Color,
)

class TextFieldColor(
    val unfocusedLabelColor: Color,
    val focusedIndicatorColor: Color,
    val unfocusedIndicatorColor: Color,
    val disabledIndicatorColor: Color,
    val errorIndicatorColor: Color,
    val cursorColor: Color,
)

class ServiceDevelopmentStatusColor(
    val approvedColor: Color,
    val discardColor: Color,
    val awaitColor: Color,
)

val lightPaletteTheme = AppColors(
    mainBackgroundColor = Color(0xFF151515),
    mainBackgroundWindowDarkColor = Color(0xFF2A2A2A),
    mainDrawerBackground = Color(0xFF252525),
    mainToolbarColor = Color(0xFF252525),
    mainLeftBarColor = Color(0xFF252525),
    mainTextColor = Color(0xFFe5e5e5),
    mainTextColorLight = Color.White,
    mainPlaceholderTextColor = Color(0xFFb2b2b2),
    mainIconsColor = Color(0xFFd4d4d4),
    mainIconsColorDark = Color(0xFF2a2a2a),
    selectedIconColor = Color(0xFF6495ED),
    cardBackgroundDark = Color(0xFF2A2A2A),
    cardBackgroundLight = Color(0xFF3A3A3D),
    tooltipAreaBackground = Color(0xFF1b1c21),
    divider = Color(0xFF212121),
    dividerLight = Color(0xFF3a3a3a),
    searchBackground = Color(0xFF262626),
    searchBackgroundDark = Color(0xFF222222),
    searchIconColor = Color(0xFF878787),
    searchDescriptionTextColor = Color(0xFFc3c3c3),
    searchDividerColor = Color(0xFF3b3b3b),
    pointerIsActiveCardColor = Color(0xFF4D4D50),
    pointerIsActiveCardColorDark = Color(0xFF3d3d40),
    linkColor = Color(0xFF4282D3),
    datePickerColors = DatePickerColors(
        containerColor = Color(0xFF212121),
        textColor = Color(0xFFe5e5e5),
        selectedTextColor = Color(0xFF0093ff),
        selectedContainerColor = Color(0xFF545454),
    ),
    errorColor = Color(0xFFFA8072),
    successColor = Color(0xFF4BB543),
    readingStatusesColor = ReadingStatusesColor(
        plannedStatusColor = Color(0xFFffbe0b),
        readingStatusColor = Color(0xFF3a86ff),
        doneStatusColor = Color(0xFF9ef01a),
        deferredStatusColor = Color(0xFFd5b9b2),
    ),
    textFieldColorOld = Color(0xFF3f3f3f),
    textFieldColorDarkOld = Color(0xFF101010),
    hintColor = Color(0xFF949494),
    focusedTextFillBackground = Color(0xFF212121),
    dropdownBackground = Color(0xFF252525),
    tooltipSelectedBackground = Color(0xFF4D4D50),
    mainAddButtonColor = Color(0xFF1CD3A2),
    textDescriptionColor = Color(0xFF949494),
    primaryButtonColor = Color(0xFF6495ED),
    secondaryButtonColor = Color(0xFF434343),
    joinAuthorsColors = JoinAuthorsColors(
        mainAuthorColor = Color(0xFF3a86ff),
        relatesAuthorsColor = Color(0xFF17B978),
    ),
    authorsContainerColor = Color(0xFF252525),
    adminPanelButtons = AdminPanelButtons(
        approvedColor = Color(0xFF8ac926),
        approvedWithChangesColor = Color(0xFFffbd00),
        disapprovedColor = Color(0xFFd00000),
        uploadColor = Color(0xFF16db65),
    ),
    titleColors = TitleColors(
        booksTitleInfoColor = Color(0xFFffbd00),
        secondaryBooksTitleInfoColor = Color(0xFF16db65),
    ),
    screenColor = ScreenColor(
        background = Color(0xFF2A2A2A),
        appBarColor = Color(0xFF252525),
        iconColor = Color(0xFFd4d4d4),
        textColor = Color(0xFFe5e5e5),
        activeLinkColor = Color(0xFF4361ee),
        activeButtonColor = Color(0xFF4361ee),
        selectedTitleTextColor = Color(0xFF4361ee),
    ),
    textFieldColor = TextFieldColor(
        unfocusedLabelColor = Color(0xFF545454),
        cursorColor = Color(0xFFd5b9b2),
        focusedIndicatorColor = Color(0xFF414141),
        unfocusedIndicatorColor = Color(0xFF414141),
        disabledIndicatorColor = Color(0xFF414141),
        errorIndicatorColor = Color(0xFFf85441),
    ),
    serviceDevelopmentStatusColor = ServiceDevelopmentStatusColor(
        approvedColor = Color(0xFF16db65),
        discardColor = Color(0xFFd00000),
        awaitColor = Color(0xFFffbe0b),
    ),
)

val darkPaletteTheme = AppColors(
    mainBackgroundColor = Color(0xFF151515),
    mainBackgroundWindowDarkColor = Color(0xFF2A2A2A),
    mainDrawerBackground = Color(0xFF252525),
    mainToolbarColor = Color(0xFF252525),
    mainLeftBarColor = Color(0xFF252525),
    mainTextColor = Color(0xFFe5e5e5),
    mainTextColorLight = Color.White,
    mainPlaceholderTextColor = Color(0xFFb2b2b2),
    mainIconsColor = Color(0xFFd4d4d4),
    mainIconsColorDark = Color(0xFF4D4D50),
    cardBackgroundDark = Color(0xFF2A2A2A),
    cardBackgroundLight = Color(0xFF3A3A3D),
    tooltipAreaBackground = Color(0xFF1b1c21),
    divider = Color(0xFF505050),
    dividerLight = Color(0xFF3a3a3a),
    searchBackground = Color(0xFF262626),
    searchBackgroundDark = Color(0xFF222222),
    searchIconColor = Color(0xFF878787),
    selectedIconColor = Color(0xFF6495ED),
    searchDescriptionTextColor = Color(0xFF9f9f9f),
    searchDividerColor = Color(0xFF9f9f9f),
    pointerIsActiveCardColor = Color(0xFF4D4D50),
    pointerIsActiveCardColorDark = Color(0xFF3d3d40),
    linkColor = Color(0xFF4282D3),
    datePickerColors = DatePickerColors(
        containerColor = Color(0xFF212121),
        textColor = Color(0xFFe5e5e5),
        selectedTextColor = Color(0xFF0093ff),
        selectedContainerColor = Color(0xFF545454),
    ),
    errorColor = Color(0xFFFA8072),
    successColor = Color(0xFF4BB543),
    readingStatusesColor = ReadingStatusesColor(
        plannedStatusColor = Color(0xFFffbe0b),
        readingStatusColor = Color(0xFF3a86ff),
        doneStatusColor = Color(0xFFccff33),
        deferredStatusColor = Color(0xFFd5b9b2),
    ),
    textFieldColorOld = Color(0xFF3f3f3f),
    textFieldColorDarkOld = Color(0xFF101010),
    hintColor = Color(0xFF949494),
    focusedTextFillBackground = Color(0xFF212121),
    dropdownBackground = Color(0xFF252525),
    tooltipSelectedBackground = Color(0xFF4D4D50),
    mainAddButtonColor = Color(0xFF1CD3A2),
    textDescriptionColor = Color(0xFF949494),
    primaryButtonColor = Color(0xFF6495ED),
    secondaryButtonColor = Color(0xFF434343),
    joinAuthorsColors = JoinAuthorsColors(
        mainAuthorColor = Color(0xFF3a86ff),
        relatesAuthorsColor = Color(0xFF17B978),
    ),
    authorsContainerColor = Color(0xFF252525),
    adminPanelButtons = AdminPanelButtons(
        approvedColor = Color(0xFF8ac926),
        approvedWithChangesColor = Color(0xFFffbd00),
        disapprovedColor = Color(0xFFd00000),
        uploadColor = Color(0xFF16db65),
    ),
    titleColors = TitleColors(
        booksTitleInfoColor = Color(0xFFffbd00),
        secondaryBooksTitleInfoColor = Color(0xFF16db65),
    ),
    screenColor = ScreenColor(
        background = Color(0xFF2A2A2A),
        appBarColor = Color(0xFF252525),
        iconColor = Color(0xFFd4d4d4),
        textColor = Color(0xFFe5e5e5),
        activeLinkColor = Color(0xFF4361ee),
        activeButtonColor = Color(0xFF4361ee),
        selectedTitleTextColor = Color(0xFF4361ee),
    ),
    textFieldColor = TextFieldColor(
        unfocusedLabelColor = Color(0xFFffbe0b),
        cursorColor = Color(0xFFd5b9b2),
        focusedIndicatorColor = Color(0xFF414141),
        unfocusedIndicatorColor = Color(0xFF414141),
        disabledIndicatorColor = Color(0xFF414141),
        errorIndicatorColor = Color(0xFFf85441),
    ),
    serviceDevelopmentStatusColor = ServiceDevelopmentStatusColor(
        approvedColor = Color(0xFF16db65),
        discardColor = Color(0xFFd00000),
        awaitColor = Color(0xFFffbe0b),
    ),
)