object Strings {
    const val list = "Список"
    const val kanban = "Доска"
    const val calendar = "Календарь"
    const val edit = "Изменить"
    const val to_main = "На главную"
    const val menu = "Меню"
    const val settings = "Настройки"
    const val another_storage = "Другое хранилище"
    const val fast_search = "Быстрый поиск"
    const val tasks = "Задачи"
    const val recent = "Недавнее"
    const val tags = "Теги"
    const val add_subtask = "Добавить подзадачу"
    const val add_bookmark = "В закладки"
    const val add_calendar = "Срок исполнения"
    const val sidebar = "Боковое меню"
    const val expand = "Развернуть"
    const val collapse = "Свернуть"
    const val close = "Закрыть"
    const val structure = "Структура"
}