const val drawable_close_icon = "close_icon.png"
const val drawable_ico = "ic.png"
const val drawable_min = "ic_min.png"
const val drawable_ic_more_button = "ic_more_button.png"
const val drawable_ic_expand_shape = "ic_expand_shape.png"