package main_models.genre

internal val genreMap = mapOf<Int, Genre>(
    1 to Genre(id = 1, name = "Художественная литература", relates = null, isSelectable = false),
    4 to Genre(id = 4, name = "Фантастика. Фэнтези", relates = 1, isSelectable = false),
    10 to Genre(id = 10, name = "Детектив. Триллер", relates = 1, isSelectable = false),
    19 to Genre(id = 19, name = "Биографии. Мемуары", relates = 1, isSelectable = false),

    2 to Genre(id = 2, name = "Современная проза", relates = 1),
    3 to Genre(id = 3, name = "Классическая проза", relates = 1),
    5 to Genre(id = 5, name = "Фэнтези", relates = 4),
    6 to Genre(id = 6, name = "Фантастический боевик", relates = 4),
    8 to Genre(id = 8, name = "Научная фантастика", relates = 4),
    7 to Genre(id = 7, name = "Мистика. Ужасы", relates = 4),
    9 to Genre(id = 9, name = "Другие жанры фантастики", relates = 4),
    11 to Genre(id = 11, name = "Детективный роман. Триллер", relates = 10),
    12 to Genre(id = 12, name = "Исторический детектив", relates = 10),
    13 to Genre(id = 13, name = "Боевик. Криминальный роман. Военный роман", relates = 10),
    14 to Genre(id = 14, name = "Другие детективные жанры", relates = 10),
    15 to Genre(id = 15, name = "Иронический детектив", relates = 10),
    16 to Genre(id = 16, name = "Любовные романы", relates = 1),
    17 to Genre(id = 17, name = "Исторические романы", relates = 1),
    18 to Genre(id = 18, name = "Приключения", relates = 1),
    20 to Genre(id = 20, name = "Деятели культуры и искусства", relates = 19),
    21 to Genre(id = 21, name = "Ученые", relates = 19),
    22 to Genre(id = 22, name = "Спортсмены", relates = 19),
    23 to Genre(id = 23, name = "Исторические и общественные деятели", relates = 19),
    24 to Genre(id = 24, name = "Бизнесмены. Истории компаний и брендов", relates = 19),
    25 to Genre(id = 25, name = "Музыканты", relates = 19),
    26 to Genre(id = 26, name = "Биографические сборники", relates = 19),
    27 to Genre(id = 27, name = "Биографии других известных людей", relates = 19),
    28 to Genre(id = 28, name = "Публицистика", relates = 1),
    29 to Genre(id = 29, name = "Поэзия", relates = 1),
    30 to Genre(id = 30, name = "Фольклор", relates = 1),
    31 to Genre(id = 31, name = "Афоризмы. Цитаты", relates = 1),
    32 to Genre(id = 32, name = "Юмор. Сатира", relates = 1),
    82 to Genre(id = 82, name = "Комиксы", relates = null),
    83 to Genre(id = 83, name = "Манга", relates = null),
    84 to Genre(id = 84, name = "Детские книги", relates = null),
    85 to Genre(id = 85, name = "Детская художественная литература", relates = 84),
    86 to Genre(id = 86, name = "Внеклассное чтение", relates = 85),
    87 to Genre(id = 87, name = "Сказки", relates = 85),
    88 to Genre(id = 88, name = "Фантастика и фэнтези для детей", relates = 85),
    89 to Genre(id = 89, name = "Повести и рассказы для детей", relates = 85),
    90 to Genre(id = 90, name = "Детский детектив", relates = 85),
    91 to Genre(id = 91, name = "Стихи и песни", relates = 85),
    92 to Genre(id = 92, name = "Фольклор и мифы для детей", relates = 85),
    93 to Genre(id = 93, name = "Детская познавательная литература", relates = 84),
    94 to Genre(id = 94, name = "Естественные науки", relates = 93),
    95 to Genre(id = 95, name = "Гуманитарные и общественные науки", relates = 93),
    96 to Genre(id = 96, name = "Техника. Программирование для детей", relates = 93),
    97 to Genre(id = 97, name = "Детские энциклопедии", relates = 93),
    98 to Genre(id = 98, name = "Мода и стиль. Этикет. Дружба", relates = 93),
    99 to Genre(id = 99, name = "Медицина и здоровье", relates = null),
    100 to Genre(
        id = 100,
        name = "Популярные системы сохранения здоровья. Здоровое питание",
        relates = 99,
    ),
    101 to Genre(id = 101, name = "Йога. Пилатес", relates = 99),
    102 to Genre(id = 102, name = "Коррекция фигуры. Диеты", relates = 99),
    103 to Genre(id = 103, name = "Фитнес. Аэробика", relates = 99),
    104 to Genre(
        id = 104,
        name = "Атласы анатомии. Медико-биологические дисциплины",
        relates = 99,
    ),
    105 to Genre(id = 105, name = "Клиническая медицина в целом", relates = 99),
    106 to Genre(id = 106, name = "Внутренние болезни", relates = 99),
    107 to Genre(id = 107, name = "Специализированные отрасли медицины", relates = 99),
    108 to Genre(id = 108, name = "Фармакология. Токсикология", relates = 99),
    109 to Genre(id = 109, name = "Педиатрия. Издания для врачей и для ВУЗов", relates = 99),
    110 to Genre(id = 110, name = "Популярная медицина", relates = 99),
    111 to Genre(
        id = 111,
        name = "Альтернативная и народная медицина. Советы целителей",
        relates = 110,
    ),
    112 to Genre(id = 112, name = "Восточная медицина", relates = 110),
    113 to Genre(id = 113, name = "Лечебное питание", relates = 110),
    114 to Genre(id = 114, name = "Массаж", relates = 110),
    115 to Genre(id = 115, name = "Научно-популярная медицинская литература", relates = 110),
    116 to Genre(id = 116, name = "Общие вопросы медицины", relates = 99),
    117 to Genre(id = 117, name = "Красота. Мода. Этикет", relates = null),
    118 to Genre(id = 118, name = "Уход за собой. Парфюмерия", relates = 117),
    119 to Genre(id = 119, name = "Гардероб. Мода. Стиль", relates = 117),
    120 to Genre(id = 120, name = "Имидж. Этикет", relates = 117),
    121 to Genre(id = 121, name = "Больше о красоте и моде", relates = 117),
    122 to Genre(id = 122, name = "Кулинария", relates = null),
    123 to Genre(id = 123, name = "Национальные кухни", relates = 122),
    124 to Genre(id = 124, name = "Поваренные книги. Сборники рецептов", relates = 122),
    125 to Genre(id = 125, name = "Консервирование", relates = 122),
    126 to Genre(id = 126, name = "Выпечка. Десерты", relates = 122),
    127 to Genre(id = 127, name = "Алкогольные напитки", relates = 122),
    128 to Genre(id = 128, name = "Безалкогольные напитки", relates = 122),
    129 to Genre(id = 129, name = "Сервировка стола. Украшение блюд", relates = 122),
    130 to Genre(id = 130, name = "Дом и хобби", relates = null),
    131 to Genre(id = 131, name = "Рукоделия и ремесла", relates = 130),
    132 to Genre(id = 132, name = "Крой и шитье", relates = 131),
    133 to Genre(id = 133, name = "Вязание. Валяние", relates = 131),
    134 to Genre(id = 134, name = "Вышивка", relates = 131),
    135 to Genre(
        id = 135,
        name = "Плетение. Работа с бумагой. Мыловарение и свечи",
        relates = 131,
    ),
    136 to Genre(id = 136, name = "Домашние ремесла", relates = 131),
    137 to Genre(id = 137, name = "Строительство. Дизайн. Приусадебный участок", relates = 130),
    138 to Genre(id = 138, name = "Дизайн интерьера. Декор", relates = 137),
    139 to Genre(id = 139, name = "Строительство, материалы и инструменты", relates = 137),
    140 to Genre(id = 140, name = "Сад. Огород. Цветоводство", relates = 137),
    141 to Genre(id = 141, name = "Домоводство", relates = 130),
    142 to Genre(id = 142, name = "Справочники по домоводству и хобби", relates = 130),
    143 to Genre(id = 143, name = "Животноводство и ветеринария", relates = 130),
    144 to Genre(id = 144, name = "Домашние питомцы", relates = 130),
    145 to Genre(id = 145, name = "Кошки", relates = 144),
    146 to Genre(id = 146, name = "Собаки", relates = 144),
    147 to Genre(id = 147, name = "Другие питомцы", relates = 144),
    148 to Genre(id = 148, name = "Коллекционирование", relates = 130),
    149 to Genre(id = 149, name = "Охота. Рыбалка. Сбор грибов и ягод", relates = 130),
    150 to Genre(id = 150, name = "Фотография", relates = 130),
    151 to Genre(id = 151, name = "Игры. Развлечения. Сценарии праздников", relates = 130),
    152 to Genre(id = 152, name = "Спорт. Самооборона", relates = 130),
    153 to Genre(id = 153, name = "Спортивные игры с мячом", relates = 152),
    154 to Genre(id = 154, name = "Шахматы", relates = 152),
    155 to Genre(id = 155, name = "Боевые искусства", relates = 152),
    156 to Genre(id = 156, name = "Другие виды спорта", relates = 152),
    157 to Genre(id = 157, name = "Общие вопросы", relates = 152),
    158 to Genre(id = 158, name = "Путешествия и туризм", relates = 130),
    159 to Genre(id = 159, name = "Путевые очерки. Травелоги", relates = 158),
    160 to Genre(
        id = 160,
        name = "Подарочные издания о туризме. Фотоальбомы о городах и странах",
        relates = 158,
    ),
    161 to Genre(id = 161, name = "Атласы и путеводители для туристов", relates = 158),
    162 to Genre(id = 162, name = "Карты городов, регионов и стран", relates = 158),
    163 to Genre(id = 163, name = "Транспорт", relates = 130),
    164 to Genre(
        id = 164,
        name = "Автомобили мира. Энциклопедии и справочники для автолюбителей",
        relates = 163,
    ),
    165 to Genre(id = 165, name = "О других видах транспорта", relates = 163),
    166 to Genre(id = 166, name = "Наука. Техника. IT", relates = null),
    167 to Genre(id = 167, name = "Технические науки", relates = 166),
    168 to Genre(id = 168, name = "Автоматика. Радиоэлектроника. Связь", relates = 166),
    169 to Genre(id = 169, name = "Энергетика. Промышленность", relates = 166),
    170 to Genre(id = 170, name = "Гражданское и промышленное строительство", relates = 166),
    171 to Genre(id = 171, name = "Физико-математические науки", relates = 166),
    172 to Genre(id = 172, name = "Математика. Научные издания", relates = 171),
    173 to Genre(id = 173, name = "Физика. Механика. Научные издания", relates = 171),
    174 to Genre(id = 174, name = "Астрономия. Научные издания", relates = 171),
    175 to Genre(id = 175, name = "Химия. Научные издания", relates = 166),
    176 to Genre(id = 176, name = "Науки о Земле. Экология", relates = 166),
    177 to Genre(id = 177, name = "Биологические науки", relates = 166),
    178 to Genre(id = 178, name = "Общая биология", relates = 177),
    179 to Genre(id = 179, name = "Биология человека. Антропология", relates = 177),
    180 to Genre(id = 180, name = "Зоология", relates = 177),
    181 to Genre(id = 181, name = "Другие биологические науки", relates = 177),
    182 to Genre(id = 182, name = "Общенаучное знание и теории", relates = 166),
    183 to Genre(id = 183, name = "Информатика", relates = 166),
    184 to Genre(id = 184, name = "Языки и среды программирования", relates = 183),
    185 to Genre(id = 185, name = "Операционные системы и программы-оболочки", relates = 183),
    186 to Genre(id = 186, name = "Прикладное программное обеспечение", relates = 183),
    187 to Genre(id = 187, name = "Компьютерные самоучители. Справочники", relates = 183),
    188 to Genre(id = 188, name = "Компьютерные сети. Интернет", relates = 183),
    189 to Genre(id = 189, name = "Аппаратное обеспечение", relates = 183),
    190 to Genre(id = 190, name = "Общие вопросы IT", relates = 183),
    191 to Genre(id = 191, name = "Религия и философия", relates = null),
    192 to Genre(id = 192, name = "Религия", relates = 191),
    193 to Genre(id = 193, name = "Религии Древнего мира. Иудаизм", relates = 192),
    194 to Genre(id = 194, name = "Христианство", relates = 192),
    195 to Genre(id = 195, name = "Православное христианство", relates = 192),
    196 to Genre(id = 196, name = "Ислам", relates = 192),
    197 to Genre(id = 197, name = "Буддизм", relates = 192),
    198 to Genre(id = 198, name = "Другие религии", relates = 192),
    199 to Genre(id = 199, name = "Теология", relates = 192),
    200 to Genre(id = 200, name = "Философия", relates = 191),
    201 to Genre(id = 201, name = "История философии", relates = 200),
    202 to Genre(id = 202, name = "Российская философия", relates = 200),
    203 to Genre(id = 203, name = "Отдельные философские науки", relates = 200),
    205 to Genre(id = 205, name = "Психология", relates = null),
    206 to Genre(id = 206, name = "Основы психологии", relates = 205),
    207 to Genre(id = 207, name = "Психологические школы и направления", relates = 205),
    208 to Genre(id = 208, name = "Психофизиология", relates = 205),
    209 to Genre(id = 209, name = "Общая теория социальной психологии", relates = 205),
    210 to Genre(id = 210, name = "Психотерапия. Психодиагностика", relates = 205),
    211 to Genre(id = 211, name = "Глубинная психология. Психоанализ", relates = 205),
    212 to Genre(id = 212, name = "НЛП", relates = 205),
    213 to Genre(id = 213, name = "Общие вопросы психологии", relates = 205),
    214 to Genre(id = 214, name = "Психология воспитания и обучения детей", relates = 205),
    215 to Genre(id = 215, name = "Психологические особенности детского возраста", relates = 205),
    216 to Genre(id = 216, name = "Больше о психологии детей", relates = 205),
    217 to Genre(id = 217, name = "Психология отношений. Семья и брак", relates = 205),
    218 to Genre(id = 218, name = "Любовь. Эротика. Секс", relates = 205),
    219 to Genre(id = 219, name = "Психология общения. Межличностные коммуникации", relates = 205),
    220 to Genre(
        id = 220,
        name = "Психология личности. Характер, темперамент, талант",
        relates = 205,
    ),
    221 to Genre(
        id = 221,
        name = "Психология успеха. Личная эффективность, мотивация",
        relates = 205,
    ),
    238 to Genre(id = 238, name = "Искусство", relates = null),
    241 to Genre(id = 241, name = "История искусств. Искусствоведение", relates = 238),
    242 to Genre(id = 242, name = "Архитектура", relates = 238),
    243 to Genre(id = 243, name = "Живопись и графика. Техники и приемы", relates = 238),
    244 to Genre(id = 244, name = "Музеи мира. Альбомы репродукций", relates = 238),
    245 to Genre(id = 245, name = "История изобразительного искусства", relates = 238),
    246 to Genre(id = 246, name = "Больше об изобразительном искусстве", relates = 238),
    247 to Genre(id = 247, name = "Интерьер. Дизайн. Оформительское искусство", relates = 238),
    248 to Genre(id = 248, name = "Театр", relates = 238),
    249 to Genre(id = 249, name = "Кино. Телевидение", relates = 238),
    250 to Genre(id = 250, name = "Больше о театре, кино и ТВ", relates = 238),
    251 to Genre(id = 251, name = "Музыка", relates = 238),
    252 to Genre(id = 252, name = "Теория и история музыки. Музыковедение", relates = 251),
    253 to Genre(id = 253, name = "Виды музыки. Либретто. Тексты", relates = 251),
    254 to Genre(id = 254, name = "Экономика. Менеджмент. Маркетинг", relates = null),
    255 to Genre(id = 255, name = "Экономика. Экономическая теория", relates = 254),
    256 to Genre(
        id = 256,
        name = "Экономическая теория. Макроэкономика. Микроэкономика",
        relates = 255,
    ),
    257 to Genre(id = 257, name = "История экономических учений", relates = 255),
    258 to Genre(
        id = 258,
        name = "Мировая экономика и международные экономические отношения. ВЭД",
        relates = 255,
    ),
    259 to Genre(id = 259, name = "Отраслевая экономика, география", relates = 255),
    260 to Genre(id = 260, name = "Личная эффективность. Мотивация", relates = 254),
    261 to Genre(
        id = 261,
        name = "Психология бизнеса. Психология успеха. Карьера. Бизнес-этикет",
        relates = 260,
    ),
    262 to Genre(
        id = 262,
        name = "Психология менеджмента. Лидерство. Мотивация. Тайм-менеджмент",
        relates = 260,
    ),
    263 to Genre(id = 263, name = "Финансы. Бухгалтерский учет. Аудит", relates = 254),
    264 to Genre(id = 264, name = "Бухгалтерский учет", relates = 263),
    265 to Genre(id = 265, name = "Деньги. Денежное обращение", relates = 263),
    266 to Genre(id = 266, name = "Финансы. Кредит. Инвестиции", relates = 263),
    267 to Genre(id = 267, name = "Ценные бумаги. Биржи (трейдинг)", relates = 263),
    268 to Genre(id = 268, name = "Аренда. Лизинг и прочие издания", relates = 263),
    269 to Genre(id = 269, name = "Бизнес. Предпринимательство. Торговля", relates = 254),
    270 to Genre(
        id = 270,
        name = "Стартап. Организация предпринимательской деятельности",
        relates = 269,
    ),
    271 to Genre(id = 271, name = "Бизнес-планирование. Основы бизнеса", relates = 269),
    272 to Genre(id = 272, name = "Торговля (коммерция)", relates = 269),
    273 to Genre(id = 273, name = "Страхование. Социальная работа", relates = 269),
    274 to Genre(
        id = 274,
        name = "Ведение переговоров. Публичные выступления. Создание презентаций",
        relates = 269,
    ),
    275 to Genre(id = 275, name = "Больше о предпринимательстве", relates = 269),
    276 to Genre(id = 276, name = "Организационный и производственный менеджмент", relates = 269),
    277 to Genre(id = 277, name = "Управление проектами", relates = 269),
    278 to Genre(id = 278, name = "Управление персоналом", relates = 269),
    279 to Genre(id = 279, name = "Общая теория менеджмента. Практические кейсы", relates = 269),
    280 to Genre(id = 280, name = "Маркетинг. Реклама", relates = 254),
    281 to Genre(id = 281, name = "Реклама. Копирайтинг. PR. Брендинг", relates = 280),
    282 to Genre(id = 282, name = "Управление продажами. Клиентоориентированность", relates = 280),
    283 to Genre(
        id = 283,
        name = "Интернет-маркетинг. Маркетинг в социальных медиасредах",
        relates = 280,
    ),
    284 to Genre(id = 284, name = "Общая теория маркетинга и рекламы", relates = 280),
    285 to Genre(id = 285, name = "История. Общество", relates = null),
    286 to Genre(id = 286, name = "Всемирная история", relates = 285),
    287 to Genre(
        id = 287,
        name = "Доисторическая эпоха. История древнего мира и античности",
        relates = 286,
    ),
    288 to Genre(id = 288, name = "История Средних веков и Возрождения", relates = 286),
    289 to Genre(
        id = 289,
        name = "История Нового и Новейшего времени (середина XVII – XXI век)",
        relates = 286,
    ),
    290 to Genre(
        id = 290,
        name = "История частей света, отдельных регионов и стран",
        relates = 286,
    ),
    291 to Genre(id = 291, name = "Общие работы по всемирной истории", relates = 286),
    292 to Genre(id = 292, name = "Российская история", relates = 285),
    293 to Genre(id = 293, name = "История Древней Руси", relates = 292),
    294 to Genre(id = 294, name = "История России до XIX века", relates = 292),
    295 to Genre(
        id = 295,
        name = "История России XIX - нач. XX веков (до 1918 г.)",
        relates = 292,
    ),
    296 to Genre(id = 296, name = "История Советского Союза", relates = 292),
    297 to Genre(id = 297, name = "Современная история России (с 1991 г)", relates = 292),
    298 to Genre(id = 298, name = "Общие работы по истории России", relates = 292),
    299 to Genre(id = 299, name = "Этнография, этнология, народоведение", relates = 285),
    300 to Genre(id = 300, name = "Политика. Социология. Культура", relates = 285),
    301 to Genre(id = 301, name = "Социология", relates = 300),
    302 to Genre(id = 302, name = "Теория и история политики", relates = 300),
    303 to Genre(id = 303, name = "Международные отношения. Внешняя политика", relates = 300),
    304 to Genre(id = 304, name = "Культура. Средства массовой информации", relates = 300),
    305 to Genre(id = 305, name = "Внутренняя политика. Внутреннее положение", relates = 300),
    306 to Genre(id = 306, name = "Теория и история политики", relates = 300),
    307 to Genre(id = 307, name = "Военное дело. Спецслужбы", relates = 285),
    308 to Genre(id = 308, name = "История военного дела", relates = 307),
    309 to Genre(id = 309, name = "Военная техника", relates = 307),
    310 to Genre(id = 310, name = "Оружие", relates = 307),
    311 to Genre(id = 311, name = "Специальные службы", relates = 307),
    312 to Genre(id = 312, name = "О военном деле и спецслужбах", relates = 307),
    313 to Genre(id = 313, name = "Биографии. Мемуары", relates = 285),
    314 to Genre(id = 314, name = "Деятели культуры и искусства", relates = 313),
    315 to Genre(id = 315, name = "Ученые", relates = 313),
    316 to Genre(id = 316, name = "Спортсмены", relates = 313),
    317 to Genre(id = 317, name = "Исторические и общественные деятели", relates = 313),
    318 to Genre(id = 318, name = "Бизнесмены. Истории компаний и брендов", relates = 313),
    319 to Genre(id = 319, name = "Музыканты", relates = 313),
    320 to Genre(id = 320, name = "Биографические сборники", relates = 313),
    321 to Genre(id = 321, name = "Биографии других известных людей", relates = 313),
    322 to Genre(id = 322, name = "Право", relates = null),
    323 to Genre(id = 323, name = "Теория и история права", relates = 322),
    324 to Genre(id = 324, name = "Международное право", relates = 322),
    325 to Genre(id = 325, name = "Конституционное и административное право", relates = 322),
    326 to Genre(
        id = 326,
        name = "Конституция и конституционный строй. Конституционное право",
        relates = 325,
    ),
    327 to Genre(id = 327, name = "Административное право", relates = 325),
    328 to Genre(
        id = 328,
        name = "Прокуратура. Следствие. Полиция. Судебная система",
        relates = 325,
    ),
    329 to Genre(
        id = 329,
        name = "Общие вопросы конституционного и административного права",
        relates = 325,
    ),
    330 to Genre(id = 330, name = "Гражданское право", relates = 322),
    331 to Genre(id = 331, name = "Общие вопросы. Гражданский кодекс", relates = 330),
    332 to Genre(
        id = 332,
        name = "Предпринимательское право. Торговое (коммерческое) право. Транспортное право",
        relates = 330,
    ),
    333 to Genre(
        id = 333,
        name = "Гражданско-процессуальное право. Арбитражно-процессуальное право",
        relates = 330,
    ),
    334 to Genre(id = 334, name = "Потребительское право", relates = 330),
    335 to Genre(id = 335, name = "Больше о гражданском праве", relates = 330),
    336 to Genre(id = 336, name = "Трудовое право", relates = 322),
    337 to Genre(id = 337, name = "Финансовое право", relates = 322),
    338 to Genre(
        id = 338,
        name = "Аграрное и земельное право. Экологическое право",
        relates = 322,
    ),
    339 to Genre(id = 339, name = "Уголовное право. Криминалистика", relates = 322),
    340 to Genre(id = 340, name = "Уголовное и уголовно-процессуальное право", relates = 339),
    341 to Genre(id = 341, name = "Криминалистика. Судебная медицина", relates = 339),
    342 to Genre(id = 342, name = "Больше об уголовном праве и криминалистике", relates = 339),
    343 to Genre(id = 343, name = "Общие вопросы права", relates = 322)
)