object Drawable {
    const val drawable_ic_more_button = "ic_more_button.png"
    const val drawable_ic_calendar = "ic_calendar.png"
    const val drawable_ic_kanban = "ic_kanban.png"
    const val drawable_ic_list = "ic_list.png"
    const val drawable_ic_plus = "ic_plus.png"
    const val drawable_ic_home = "ic_home.png"
    const val drawable_ic_sidebar = "ic_sidebar.png"
    const val drawable_ic_settings = "ic_settings.png"
    const val drawable_ic_folder = "ic_folder.png"
    const val drawable_ic_search = "ic_search.png"
    const val drawable_ic_timer_off = "ic_timer_off.png"
    const val drawable_ic_timer_on = "ic_timer_on.png"
    const val drawable_ic_activity = "ic_activity.png"
    const val drawable_ic_tag = "ic_tag.png"
    const val drawable_ic_random = "ic_random.png"
    const val drawable_ic_search_glass = "ic_search_glass.png"
    const val drawable_ic_empty_search = "ic_empty_search.png"
    const val drawable_ic_task = "ic_task.png"
    const val drawable_ic_subtask = "ic_subtask.png"
    const val drawable_ic_bookmark = "ic_bookmark.png"
    const val drawable_ic_close = "ic_close.png"
    const val drawable_ic_expand = "ic_expand.png"
    const val drawable_ic_collapse = "ic_collapse.png"
    const val drawable_ic_note_sidebar = "ic_note_sidebar.png"
    const val drawable_ic_structure = "ic_structure.png"
    const val drawable_ic_expand_shape = "ic_expand_shape.png"
}