package main_models.rating_review

class ReviewAndRatingVo(
    val localId: Int?,
    val id: Int?,
    val ratingScore: Int,
    val reviewText: String?,
    val bookId: String,
    val bookAuthorId: String,
    val userId: Int,
    val userName: String,
    val likesCount: Int?,
    val dislikesCount: Int?,
    val answersCount: Int?,
    val isApprovedReview: Boolean,
    val isDisapprovedReview: Boolean,
    val timestampOfCreatingScore: Long,
    val timestampOfUpdatingScore: Long,
    val timestampOfCreatingReview: Long,
    val timestampOfUpdatingReview: Long,
    val updatedByDeviceId: String?,
    val bookGenreId: Int,
    val isCreatedManuallyBook: Boolean,
    val bookForAllUsers: Boolean,
) {

    companion object {
        fun createEmptyRating(
            rating: Int,
            bookId: String,
            bookAuthorId: String,
            bookGenreId: Int,
            isCreatedManuallyBook: Boolean,
            bookForAllUsers: Boolean,
            userId: Int,
            userName: String,
            deviceId: String,
            timestamp: Long
        ): ReviewAndRatingVo = ReviewAndRatingVo(
            id = null,
            localId = null,
            ratingScore = rating,
            reviewText = null,
            bookId = bookId,
            bookAuthorId = bookAuthorId,
            userId = userId,
            userName = userName,
            likesCount = 0,
            dislikesCount = 0,
            answersCount = 0,
            isApprovedReview = false,
            isDisapprovedReview = false,
            timestampOfCreatingScore = timestamp,
            timestampOfUpdatingScore = timestamp,
            timestampOfCreatingReview = 0,
            timestampOfUpdatingReview = 0,
            updatedByDeviceId = deviceId,
            bookGenreId = bookGenreId,
            isCreatedManuallyBook = isCreatedManuallyBook,
            bookForAllUsers = bookForAllUsers,
        )

        fun createEmptyReview(
            rating: Int,
            bookId: String,
            bookAuthorId: String,
            bookGenreId: Int,
            isCreatedManuallyBook: Boolean,
            bookForAllUsers: Boolean,
            userId: Int,
            userName: String,
            deviceId: String,
            timestamp: Long
        ): ReviewAndRatingVo = ReviewAndRatingVo(
            id = null,
            localId = null,
            ratingScore = rating,
            reviewText = null,
            bookId = bookId,
            bookAuthorId = bookAuthorId,
            userId = userId,
            userName = userName,
            likesCount = 0,
            dislikesCount = 0,
            answersCount = 0,
            isApprovedReview = false,
            isDisapprovedReview = false,
            timestampOfCreatingScore = timestamp,
            timestampOfUpdatingScore = timestamp,
            timestampOfCreatingReview = 0,
            timestampOfUpdatingReview = 0,
            updatedByDeviceId = deviceId,
            bookGenreId = bookGenreId,
            isCreatedManuallyBook = isCreatedManuallyBook,
            bookForAllUsers = bookForAllUsers,
        )
    }
}