package main_models.books

enum class LANG(val value: String, val translatedName: String) {
    RUSSIAN("RU", "Русский"),
    ENGLISH("EN", "Английский"),
    SPANISH("ES", "Испанский"),
    FRENCH("FR", "Французский"),
    GERMAN("DE", "Немецкий"),
    UKRAINIAN("UK", "Украинский"),
    CHINESE("ZH", "Китайский"),
    KOREAN("KO", "Корейский"),
    JAPANESE("JA", "Японский"),
    ITALIAN("IT", "Итальянский"),
    PORTUGUESE("PT", "Португальский"),
    ARABIC("AR", "Арабский"),
    TURKISH("TR", "Турецкий"),
    DUTCH("NL", "Нидерландский"),
    POLISH("PL", "Польский"),
    SWEDISH("SV", "Шведский"),
    DANISH("DA", "Датский"),
    FINNISH("FI", "Финский"),
    NORWEGIAN("NO", "Норвежский"),
    GREEK("EL", "Греческий"),
    CZECH("CS", "Чешский"),
    HEBREW("HE", "Иврит"),
    THAI("TH", "Тайский"),
    INDONESIAN("ID", "Индонезийский"),
    VIETNAMESE("VI", "Вьетнамский"),
    HINDI("HI", "Хинди"),
    MALAY("MS", "Малайский"),
    TAMIL("TA", "Тамильский"),
    TELUGU("TE", "Телугу"),
    BENGALI("BN", "Бенгальский"),
    HUNGARIAN("HU", "Венгерский"),
    ROMANIAN("RO", "Румынский"),
}